# not to be used in production
version: "3"

services:
    a11y:
        build: .
        ports:
            - 3000:3000
        environment: 
            - MONGODB_URI=mongodb://mongo:27017/a11y-req
            - BASIC_AUTH_USERNAME=admin
            - BASIC_AUTH_PASSWORD=password
            - POPULATE_DB=$${POPULATE_DB}
            - WAIT_HOSTS=mongo:27017
            - WAIT_FOR_MONGO=true
        depends_on:
            - mongo

    mongo:
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: always
    
    mongoexpress:
        image: mongo-express
        restart: always
        ports: 
            - 3005:8081
        depends_on:
            - mongo

