version: "3"

services:
  a11y:
    build: .
    ports:
      - "${PORT:-80}:80"   # Dynamically bind the container port to the host port specified by the environment variable
    environment:
      - MONGODB_URI=mongodb://mongo/a11y-req
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=password
      - POPULATE_DB=$${POPULATE_DB}
      - WAIT_HOSTS=mongo:27017
      - WAIT_FOR_MONGO=true
      - PORT=$PORT     # Pass the dynamic port to the container (optional, if your app uses this)
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:3.3
    restart: always
    networks:
      - backend

  mongoexpress:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"   # Expose mongoexpress on port 8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - backend

networks:
  backend:
    driver: bridge
